### ISSUE TITLE
missing (404) links

### ISSUE THREAD

**Issue by thinrope** [pcengines/pcengines.github.io#21]
While working on something else, I hit a few dead links, so I run a random free tool and it came back with 9 [edit: 2] missing, namely:

- [x] https://pcengines.ch/file/apu5_v4.6.2.rom.tar.gz
- [x] https://pcengines.ch/file/apu2_v4.6.2.rom.tar.gz
- [x] https://pcengines.ch/file/apu3_v4.6.2.rom.tar.gz
- [x] https://pcengines.ch/file/apu2_v4.0.13.rom.tar.gz
- [x] https://pcengines.ch/file/apu3_v4.0.13.rom.tar.gz
- [x] https://pcengines.ch/file/apu2_v4.0.10.rom.tar.gz
- [x] https://pcengines.ch/file/apu3_v4.0.10.rom.tar.gz
- [x] https://pcengines.ch/file/apu2_v4.0.9.rom.tar.gz
- [x] https://pcengines.ch/file/apu5_v4.0.13.rom.tar.gz

Not sure if this html is generated by a script or not (it is not in the repo anyway), but please have a look and fix, either:
* upload the missing files to pcengines.ch
* remove from the index

**Comment by michaelsteinmann** [comment]
Thanks, missing files uploaded.
But I'm, missing the following two files:
https://pcengines.ch/file/apu2_v4.0.10.rom.tar.gz
https://pcengines.ch/file/apu3_v4.0.10.rom.tar.gz


Am Fr., 21. Dez. 2018 um 10:16 Uhr schrieb Kalin KOZHUHAROV <
notifications@github.com>:

**Comment by pietrushnic** [comment]
@michaelsteinmann apu2: https://cloud.3mdeb.com/index.php/s/kH2Ylw5VIpKwQiz
apu3: https://cloud.3mdeb.com/index.php/s/ZZnl2CegaCc0zyK

**Comment by michaelsteinmann** [comment]
copied

Am Fr., 21. Dez. 2018 um 13:22 Uhr schrieb Piotr Król <
notifications@github.com>:

**Comment by thinrope** [comment]
So, marking this as fixed! Great response time :-)
