### ISSUE TITLE
Release v4.9.0.1 missing

### ISSUE THREAD

**Issue by b-bittner** [pcengines/pcengines.github.io#22]
Hi,
I'm not quite sure if this is the right place/way to ask for this.
Is there a reason why the newest Coreboot-Release (v4.9.0.1) is missing in the official [documentation](https://pcengines.github.io/) ?

**Comment by pietrushnic** [comment]
@b-bittner it is fine. I get the same question over PC Engines forum. This was my fault and mess caused by not adding binaries to the first newsletter. We will improve that soon - Monday EOD website should be fixed.

**Comment by miczyg1** [comment]
@b-bittner v4.9.0.1 release has been added. I am closing the issue.

**Comment by b-bittner** [comment]
@**all**, thanks for uploading and updating the page. Would it be possible to add md5-sum files to the tar-archive, like in the releases before?

**Comment by miczyg1** [comment]
@b-bittner we began to sign the images. We will upgrade the site soon with SHA256 signatures and digests, so that everyone could verify the binaries.

**Comment by b-bittner** [comment]
@miczyg1 ah, that's nice. Looking forward for it.
