### ISSUE TITLE
cloud.3mdeb.com seems down so dl links do not work

### ISSUE THREAD

**Issue by KEZHwMlXV1vFzs6QvY8v5WjX5** [pcengines/pcengines.github.io#36]
https://www.isitdownrightnow.com/cloud.3mdeb.com.html

**Comment by pietrushnic** [comment]
Thank you for reporting the issue. We are aware of the problem and working to fix it. Short term mitigation would be to bring back cloud.3mdeb.com. Long Term we will move to more reliable hosting.
