### ISSUE TITLE
Release 4.0.30 missing

### ISSUE THREAD

**Issue by x-jokay** [pcengines/pcengines.github.io#59]
Release [4.0.30](https://gitlab.com/pcengines/coreboot/-/commits/rel_4.0.30) is missing on [index.html](https://github.com/pcengines/pcengines.github.io/blob/master/index.html).

**Comment by miczyg1** [comment]
@x-jokay tag is on the repository, true, but the binaries are under regression testing. They will appear on the site on thursday or friday. The pull request is already done and awaits the results from tests:
https://github.com/pcengines/pcengines.github.io/pull/58

**Comment by x-jokay** [comment]
@miczyg1 sure, but then you shouldn't mention it (yet) on the current [index.html](https://github.com/pcengines/pcengines.github.io/blob/master/index.html#L128).

**Comment by miczyg1** [comment]
I do not see any reason why shouldn't I inform the community earlier that they should verify v4.0.30 and later with a newer key. If I created confusion, I'm sorry.
